### ISSUE TITLE
fs-extra issue on Mac

### ISSUE THREAD

**Issue by plusinvenco** [danieluhm2004/serverless-webpack-prisma#3] opened 2022-01-12 04:26 UTC
I ran into the similar fs-extra issue reported in https://issueexplorer.com/issue/jprichardson/node-fs-extra/926

This only occurs when I attempt to run `sls package` or `invoke local` on my mac locally.

It is working fine on my CI which uses a different environment.

```
plusinvenco@INV-016-Plus my-service % sls package
Serverless: Running "serverless" installed locally (in service node_modules)

 Type Error ----------------------------------------------

  TypeError: Cannot read property 'name' of undefined
      at exports.fromCallback (/Users/plusinvenco/Projects/my-service/node_modules/universalify/index.js:15:26)
      at Object.<anonymous> (/Users/plusinvenco/Projects/my-service/node_modules/serverless-webpack-prisma/node_modules/fs-extra/lib/fs/index.js:57:27)
      at Module._compile (internal/modules/cjs/loader.js:1198:30)
      at Module._compile (pkg/prelude/bootstrap.js:1394:32)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
      at Module.load (internal/modules/cjs/loader.js:1047:32)
      at Function.Module._load (internal/modules/cjs/loader.js:935:14)
      at Module.require (internal/modules/cjs/loader.js:1087:19)
      at Module.require (pkg/prelude/bootstrap.js:1338:31)
      at require (internal/modules/cjs/helpers.js:73:18)
      at Object.<anonymous> (/Users/plusinvenco/Projects/my-service/node_modules/serverless-webpack-prisma/node_modules/fs-extra/lib/index.js:5:6)
      at Module._compile (internal/modules/cjs/loader.js:1198:30)
      at Module._compile (pkg/prelude/bootstrap.js:1394:32)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
      at Module.load (internal/modules/cjs/loader.js:1047:32)
      at Function.Module._load (internal/modules/cjs/loader.js:935:14)
      at Module.require (internal/modules/cjs/loader.js:1087:19)
      at Module.require (pkg/prelude/bootstrap.js:1338:31)
      at require (internal/modules/cjs/helpers.js:73:18)
      at Object.<anonymous> (/Users/plusinvenco/Projects/my-service/node_modules/serverless-webpack-prisma/src/index.js:5:13)
      at Module._compile (internal/modules/cjs/loader.js:1198:30)
      at Module._compile (pkg/prelude/bootstrap.js:1394:32)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
      at Module.load (internal/modules/cjs/loader.js:1047:32)
      at Function.Module._load (internal/modules/cjs/loader.js:935:14)
      at Module.require (internal/modules/cjs/loader.js:1087:19)
      at Module.require (pkg/prelude/bootstrap.js:1338:31)
      at require (internal/modules/cjs/helpers.js:73:18)
      at requireServicePlugin (/Users/plusinvenco/Projects/my-service/node_modules/serverless/lib/classes/PluginManager.js:34:12)
      at /Users/plusinvenco/Projects/my-service/node_modules/serverless/lib/classes/PluginManager.js:178:22
      at Array.map (<anonymous>)
      at PluginManager.resolveServicePlugins (/Users/plusinvenco/Projects/my-service/node_modules/serverless/lib/classes/PluginManager.js:175:10)
      at PluginManager.loadAllPlugins (/Users/plusinvenco/Projects/my-service/node_modules/serverless/lib/classes/PluginManager.js:158:10)
      at Serverless.init (/Users/plusinvenco/Projects/my-service/node_modules/serverless/lib/Serverless.js:213:30)
      at async Serverless.eventuallyFallbackToLocal (/snapshot/serverless/lib/Serverless.js:270:5)
      at async Serverless.init (/snapshot/serverless/lib/Serverless.js:197:5)
      at async /snapshot/serverless/scripts/serverless.js:505:7

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.55.0 (standalone)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.15.1
```

**Comment by plusinvenco** [comment] 2022-01-12 04:46
Forgot to mention, my project is in TypeScript.

**Comment by danieluhm2004** [comment] 2022-01-12 09:27
Hello.

After checking the error you mentioned, it is confirmed that an error occurs in the process of executing the `fs.realpath.native` function process in `fs-extra`.

`fs.realpath.native` is a function added after **Node.js v9.2.0**. May I know which Node.js version you are using?

thank you.

**Comment by plusinvenco** [comment] 2022-01-12 22:36
@danieluhm2004 I tried
node/12.17.0
node/12.22.0
node/16.13.2
All of them produce the same error.

Plus, node/12.xx.x also threw another error at line `return this.serverless.service?.custom?.webpack?.packager || 'npm';`
However, this error is resolved simply by upgrading the node.

**Comment by plusinvenco** [comment] 2022-01-12 22:40
I came across [this comment](https://github.com/jprichardson/node-fs-extra/issues/743#issuecomment-580346768) and [this one](https://stackoverflow.com/questions/43112619/typescript-require-statement-not-part-of-an-import-statement/43112861#43112861) which may explain why the issue is caused for Typescript.

**Comment by danieluhm2004** [comment] 2022-01-15 08:46
Hello @plusinvenco :)

First, we confirmed that the optional chaining you mentioned did not work in node v12 and corrected it. It will be changed to be available in the next version.

However, the error related to fs-extra that you mentioned is not implemented in my Mac (m1). If it's okay, could you please share the project with the symptom as a link to the github repository?

\+ Due to the version-specific errors you mentioned, we plan to add automatic version-specific tests through GitHub Actions in the future.

Thank you so much for always helping.

**Comment by plusinvenco** [comment] 2022-01-18 22:43
Hi @danieluhm2004 

Thanks for taking a look at the issues. Unfortunately, I couldn't share the project as it's a private repo and not owned by me. 

However, when I get time, I'll create a separate public project that produces the same issue, and share it with you if that helps.

**Comment by bgswilde** [comment] 2022-02-08 22:33
@plusinvenco Having a similar issue, were you able to come to a solution?

**Comment by plusinvenco** [comment] 2022-02-09 00:02
> @plusinvenco Having a similar issue, were you able to come to a solution?

@bgswilde I haven't been using `sls package` or `invoke local` since my previous comment. However, I tried again right after I saw your comment, and it seems fixed. I can use these commands with no issues now. 

One thing to note though, I have upgraded the serverless framework to v3.0.1, not sure if this fixed the issue, but that's the only thing I did.

**Comment by danieluhm2004** [comment] 2022-02-10 06:40
Hello.

It's a pity that the cause is unknown, but I'm glad it's been resolved! 

@bgswilde Please check it out and share the information if it doesn't work. :)

Thank you.

**Comment by danieluhm2004** [comment] 2022-02-17 04:11
I will close the issue. If you have any related issues, please open it again. :)

**Closed as completed by danieluhm2004** 2022-02-17 04:11 UTC

**Comment by plusinvenco** [comment] 2022-02-17 06:17
@danieluhm2004 Cheers!
